import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>UPTA DEMO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1 className={styles.headings}>
            The Universal Public Transport Application
          </h1>
          <div>
            <a>
              <Image
                src="/UPTAlogo.png"
                alt="UPTA Logo"
                className={styles.logo}
                width={225}
                height={125}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/solid-emblem.svg"
            alt="Next.js Logo"
            width={180}
            height={160}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/UUlogo.png"
              alt="13"
              width={500}
              height={75}
              priority
            />
          </div>
        </div>
        {/* These are the login buttons*/}
        <div className={styles.login_buttons_grid}>
          <a
            href="/login_company/company_login_p"
            className={styles.login_cards}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Company Login <span>-&gt;</span>
            </h2>
            <p>
              Log in for commercial entities
            </p> 
          </a>
          <a
            href="/login_user/user_login_p"
            className={styles.login_cards}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              User Login <span>-&gt;</span>
            </h2>
            <p>
              Log in for users
            </p> 
          </a>
          


        </div>

        <div className={styles.grid}>
          <a
            href="/about/about"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              About <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn more about the project.
            </p>
          </a>

          <a
            //REPLACE WITH GITHUB REPO ONCE SETUP
            href="https://github.com/jzvolensky/upta-demo"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Github repo <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              To view and access the source code click here!
            </p>
          </a>

          <a
            href="https://solidproject.org/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              The Solid Project <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Explore the world of interoperability and security
            </p>
          </a>

          <a
            href="/changelog/changelog"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Changelog <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              View all of the new exciting features available on UPTA!
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
